const eventList = 
  {
    events: [
      {
        eventName: "Music Room",
        eventDescription:
          "We are organizing an in-house music jamming session at our cafe. There will be music, drinks, and a lot of fun. It is open for people of age range 18-40.",
        eventStartTime: "2023-07-15T19:00:00",
        eventEndTime: "2023-07-15T23:00:00",
        eventDuration: "4 hours",
        eventLocation: "Melody Cafe, 123 Harmony Street",
        host_id: "host001",
        isBusiness: true,
        eventId: "unique1234",
        registrationFee: "500",
        maxCapacity: "30",
      },
      {
        eventName: "Yoga in the Park",
        eventDescription:
          "Start your day with a refreshing yoga session in the heart of nature. Suitable for all levels, bring your own mat.",
        eventStartTime: "2023-07-20T07:00:00",
        eventEndTime: "2023-07-20T08:30:00",
        eventDuration: "1.5 hours",
        eventLocation: "Central Park, Near the Lake",
        host_id: "host002",
        isBusiness: false,
        eventId: "unique5678",
        registrationFee: "0",
        maxCapacity: "50",
      },
      {
        eventName: "Cooking Masterclass: Italian Cuisine",
        eventDescription:
          "Learn to cook authentic Italian dishes from a professional chef. Ingredients provided, just bring your enthusiasm!",
        eventStartTime: "2023-07-25T18:00:00",
        eventEndTime: "2023-07-25T21:00:00",
        eventDuration: "3 hours",
        eventLocation: "Gourmet Kitchen Studio, 456 Flavour Avenue",
        host_id: "host003",
        isBusiness: true,
        eventId: "unique9101",
        registrationFee: "1500",
        maxCapacity: "20",
      },
      {
        eventName: "Tech Startup Networking",
        eventDescription:
          "Connect with fellow entrepreneurs, investors, and tech enthusiasts. Great opportunity for networking and sharing ideas.",
        eventStartTime: "2023-08-02T17:00:00",
        eventEndTime: "2023-08-02T20:00:00",
        eventDuration: "3 hours",
        eventLocation: "Innovation Hub, 789 Silicon Street",
        host_id: "host004",
        isBusiness: true,
        eventId: "unique1121",
        registrationFee: "200",
        maxCapacity: "100",
      },
      {
        eventName: "Weekend Hiking Adventure",
        eventDescription:
          "Explore the beautiful trails of Mountain National Park. Intermediate level hike, breathtaking views guaranteed!",
        eventStartTime: "2023-08-05T09:00:00",
        eventEndTime: "2023-08-05T16:00:00",
        eventDuration: "7 hours",
        eventLocation: "Mountain National Park, Trail Head Parking",
        host_id: "host005",
        isBusiness: false,
        eventId: "unique3141",
        registrationFee: "50",
        maxCapacity: "25",
      },
      {
        eventName: "Artisan Craft Fair",
        eventDescription:
          "Discover unique handmade crafts from local artisans. Perfect for finding one-of-a-kind gifts or treating yourself!",
        eventStartTime: "2023-08-12T10:00:00",
        eventEndTime: "2023-08-12T18:00:00",
        eventDuration: "8 hours",
        eventLocation: "Community Center, 321 Craft Lane",
        host_id: "host006",
        isBusiness: true,
        eventId: "unique5161",
        registrationFee: "0",
        maxCapacity: "500",
      },
      {
        eventName: "Salsa Dance Workshop",
        eventDescription:
          "Learn the basics of salsa dancing or improve your technique. No partner needed, all levels welcome!",
        eventStartTime: "2023-08-18T19:30:00",
        eventEndTime: "2023-08-18T21:30:00",
        eventDuration: "2 hours",
        eventLocation: "Rhythm Dance Studio, 654 Salsa Street",
        host_id: "host007",
        isBusiness: true,
        eventId: "unique7181",
        registrationFee: "300",
        maxCapacity: "40",
      },
      {
        eventName: "Sunset Beach Cleanup",
        eventDescription:
          "Join us in keeping our beaches clean! Equipment provided. Let's make a difference while enjoying a beautiful sunset.",
        eventStartTime: "2023-08-22T17:30:00",
        eventEndTime: "2023-08-22T19:30:00",
        eventDuration: "2 hours",
        eventLocation: "Sunny Beach, Main Entrance",
        host_id: "host008",
        isBusiness: false,
        eventId: "unique9202",
        registrationFee: "0",
        maxCapacity: "100",
      },
      {
        eventName: "Virtual Reality Gaming Tournament",
        eventDescription:
          "Compete in various VR games and win exciting prizes! Whether you're a pro or new to VR, there's fun for everyone.",
        eventStartTime: "2023-08-28T13:00:00",
        eventEndTime: "2023-08-28T20:00:00",
        eventDuration: "7 hours",
        eventLocation: "GameZone VR Arena, 987 Digital Drive",
        host_id: "host009",
        isBusiness: true,
        eventId: "unique2122",
        registrationFee: "750",
        maxCapacity: "60",
      },
      {
        eventName: "Community Garden Workshop",
        eventDescription:
          "Learn sustainable gardening techniques and help plant our community garden. Great for beginners and experienced gardeners alike!",
        eventStartTime: "2023-09-02T09:00:00",
        eventEndTime: "2023-09-02T12:00:00",
        eventDuration: "3 hours",
        eventLocation: "Green Thumb Community Center, 159 Blossom Road",
        host_id: "host010",
        isBusiness: false,
        eventId: "unique2324",
        registrationFee: "100",
        maxCapacity: "35",
      },
    ],
  }

export default eventList;
